## 一、定义前向、后向传播

本文将用numpy实现全连接层的前向过程和反向过程，并使用一个线性回归作为例子进行测试；

如果对神经网络的反向传播过程还有不清楚的，可以[0_1-全连接层、损失函数的反向传播](0_1-全连接层、损失函数的反向传播.md)


In [44]:
import numpy as np

def fc_forword(z, W, b):
    """
    全连接层的前向传播
    :param z: 当前层的输出
    :param W: 当前层的权重
    :param b: 当前层的偏置
    :return: 下一层的输出
    """
    return np.dot(z, W) + b


def fc_backword(next_dz, W, z):
    """
    全连接层的反向传播
    :param next_dz: 下一层的梯度
    :param W: 当前层的权重
    :param z: 当前层的输出
    :return:
    """
    dz = np.dot(next_dz, W.T)  # 当前层的梯度
    dw = np.dot(z.T, next_dz)  # 当前层权重的梯度
    db = np.sum(next_dz,axis=0)  # 当前层偏置的梯度
    return dw, db, dz

## 二、定义损失函数

In [45]:
def mean_squared_loss(y_predict,y_true):
    """
    均方误差损失函数
    :param y_predict: 预测值,shape (N,d)，N为批量样本数
    :param y_true: 真实值
    :return:
    """
    loss = np.mean(np.sum(np.square(y_predict-y_true),axis=-1))  # 损失函数值
    dy = y_predict - y_true  # 损失函数关于网络输出的梯度
    return loss, dy

## 三、初始化数据

In [46]:

# 实际的权重和偏置
W = np.array([[3,7,4],
              [5,2,6]])
b = np.array([2,9,3])

# 产生训练样本
x_data = np.random.randint(0,10,1000).reshape(500,2)
y_data = np.dot(x_data,W)+b

def next_sample(batch_size=1):
    idx=np.random.randint(500)
    return x_data[idx:idx+batch_size],y_data[idx:idx+batch_size]

print("x.shape:{},y.shape:{}".format(x_data.shape,y_data.shape))

x.shape:(500, 2),y.shape:(500, 3)


## 四、定义网络、使用SGD训练

In [47]:
# 随机初始化参数
W1 = np.random.randn(2,3)
b1 = np.zeros([3])
loss = 100.0
lr = 0.01
i = 0 

while loss > 1e-20:
    x,y_true=next_sample(4)  # 获取当前样本
    # 前向传播
    y = fc_forword(x,W1,b1)
    # 反向传播更新梯度
    loss,dy=mean_squared_loss(y,y_true)
    dw,db,_ = fc_backword(dy,W,x)
    
    # 在一个batch中梯度取均值
    #print(dw)
    
    # 更新梯度
    W1 -= lr*dw
    b1 -= lr*db
    
    # 更新迭代次数
    i += 1
    if i % 1000 == 0:
        print("\n迭代{}次，当前loss:{}, 当前权重:{},当前偏置{}".format(i,loss,W1,b1))   

# 打印最终结果
print("\n迭代{}次，当前loss:{}, 当前权重:{},当前偏置{}".format(i,loss,W1,b1))  


迭代1000次，当前loss:6.71641270857867e-05, 当前权重:[[2.99972146 6.99852611 3.99961782]
 [4.99974163 1.99863279 5.99964548]],当前偏置[1.9993671  8.99665095 2.99913158]

迭代2000次，当前loss:8.195215410674745e-11, 当前权重:[[2.99999978 6.99999886 3.9999997 ]
 [4.99999964 1.99999812 5.99999951]],当前偏置[2.00000169 9.00000895 3.00000232]

迭代3000次，当前loss:4.597838908503367e-18, 当前权重:[[3. 7. 4.]
 [5. 2. 6.]],当前偏置[2. 9. 3.]

迭代3203次，当前loss:6.042941525544044e-21, 当前权重:[[3. 7. 4.]
 [5. 2. 6.]],当前偏置[2. 9. 3.]


In [48]:
print("W1==W: {} \nb1=b:  {}".format(np.allclose(W1,W),np.allclose(b1,b)))

W1==W: True 
b1=b:  True
